src/pyramid/storehouse/pojo/Item.java
package pyramid.storehouse.pojo;


import java.util.Date;


public class Item implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4356588800622239863L;
	private int itemId;
	private String name;
	private String unit;
	private Date dateAdded;

	public Item() {
	}

	public Item(int itemId, Date dateAdded) {
		this.itemId = itemId;
		this.dateAdded = dateAdded;
	}

	public Item(int itemId, String name, Date dateAdded) {
		this.itemId = itemId;
		this.name = name;
		this.dateAdded = dateAdded;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public void reset () {
		this.itemId = 0;
		this.name = null;
		this.unit = null;
		this.dateAdded = null;
	}

	public String save () {
		
		return "";
	}
	
	@Override
	public String toString() {
		return "Item [itemId=" + itemId + ", name=" + name + ", unit=" + unit
				+ ", dateAdded=" + dateAdded + "]";
	}
}

src/pyramid/storehouse/pojo/Role.java
package pyramid.storehouse.pojo;

import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.primefaces.context.RequestContext;

import pyramid.storehouse.dao.RoleDao;

@ManagedBean
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -162238534183783160L;
	private Integer roleId;
	private String roleName;
	private String description;
	private String read;
	private String write;
	private String modify;
	private String delete;
	private Date dateAdded;
	private String selectedRole;
	private List<Role> roles;
	
	@ManagedProperty("#{roleDao}")
	private RoleDao roleDao;

	public Role() {
	}
	
	public Role(int roleId, String roleName, String description) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.description = description;
	}

	public Role(String roleName, String description, String read, String write,
			String modify, String delete) {
		this.roleName = roleName;
		this.description = description;
		this.read = read;
		this.write = write;
		this.modify = modify;
		this.delete = delete;
	}

	public Role(String roleName, String description, String read, String write,
			String modify, String delete, Date dateAdded) {
		this.roleName = roleName;
		this.description = description;
		this.read = read;
		this.write = write;
		this.modify = modify;
		this.delete = delete;
		this.dateAdded = dateAdded;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRead() {
		return this.read;
	}

	public void setRead(String read) {
		this.read = read;
	}

	public String getWrite() {
		return this.write;
	}

	public void setWrite(String write) {
		this.write = write;
	}

	public String getModify() {
		return this.modify;
	}

	public void setModify(String modify) {
		this.modify = modify;
	}

	public String getDelete() {
		return this.delete;
	}

	public void setDelete(String delete) {
		this.delete = delete;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public void showRoleSelect() {
		System.out.println ("Fired");
        Map<String,Object> options = new HashMap<String, Object>();
        options.put("modal", true);
        options.put("width", 640);
        options.put("height", 340);
        options.put("contentWidth", "100%");
        options.put("contentHeight", "100%");
        options.put("headerElement", "customheader");

        HttpServletRequest request = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();

        Map<String, List<String>> params = new HashMap<String, List<String>>();
        params.put("ck", Arrays.asList(request.getParameter("ck")));
        RequestContext.getCurrentInstance().openDialog("role.xhtml", options, params);
    //    return "role.xhtml";
    }
	
	public void searchRole () {
		System.out.println("Searching for Roles");
	}

	@PostConstruct
	public void showRoles () {
		roles = roleDao.getAllRoles();
	}
	
	@Override
	public String toString() {
		return "Role [roleId=" + roleId + ", roleName=" + roleName
				+ ", description=" + description + ", read=" + read
				+ ", write=" + write + ", modify=" + modify + ", delete="
				+ delete + ", dateAdded=" + dateAdded + "]";
	}

	public String getSelectedRole() {
		return selectedRole;
	}

	public void setSelectedRole(String selectedRole) {
		this.selectedRole = selectedRole;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public RoleDao getRoleDao() {
		return roleDao;
	}

	public void setRoleDao(RoleDao roleDao) {
		this.roleDao = roleDao;
	}
}

src/pyramid/storehouse/pojo/Stock.java
package pyramid.storehouse.pojo;

import java.util.Date;

public class Stock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6659622279611936526L;
	private String stockId;
	private String supplierId;
	private String supplierName;
	private String itemId;
	// Used only for Showing Stocks
	private String itemName;
	private String employeeId;
	private String storeId;
	private String operation;
	
	private String quantity;

	private String driverMobile;

	private String vehicleRegNum;
	private Date entryDate;
	private Date modifyDate;
	private String remarks;

	public Stock() {
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getStoreId() {
		return storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public String getDriverMobile() {
		return driverMobile;
	}

	public void setDriverMobile(String driverMobile) {
		this.driverMobile = driverMobile;
	}

	public String getVehicleRegNum() {
		return vehicleRegNum;
	}

	public void setVehicleRegNum(String vehicleRegNum) {
		this.vehicleRegNum = vehicleRegNum;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getStockId() {
		return stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public String getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public void reset () {

		supplierId = null;
		supplierName = null;
		itemId = null;
		employeeId = null;
		storeId = null;
		operation = null;
		quantity = null;
		driverMobile = null;
		vehicleRegNum = null;
		entryDate = null;
		modifyDate = null;
		remarks = null;
	}

	@Override
	public String toString() {
		return "Stock [stockId=" + stockId + ", supplierId=" + supplierId
				+ ", supplierName=" + supplierName + ", itemId=" + itemId
				+ ", employeeId=" + employeeId + ", storeId=" + storeId
				+ ", operation=" + operation + ", quantity=" + quantity
				+ ", driverMobile=" + driverMobile + ", vehicleRegNum="
				+ vehicleRegNum + ", entryDate=" + entryDate + ", modifyDate="
				+ modifyDate + ", remarks=" + remarks + "]";
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}
}

src/pyramid/storehouse/pojo/Store.java
package pyramid.storehouse.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Store implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4201333085399843066L;

	private int storeId;

	private String storeName;

	private String address;
	private String city;
	private String state;
	private String country;

	private String pincode;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date startDate;
	private Date closeDate;

	// Used for Date
	private String date_1_1;
	// Used for Month
	private String date_1_2;
	// Used for Year
	private String date_1_3;
	
	private String empid;

	public Store() {
	}

	public Store(int storeId, String storeName, String address, Date startDate) {
		this.storeId = storeId;
		this.storeName = storeName;
		this.address = address;
		this.startDate = startDate;
	}

	public Store(int storeId, String storeName, String address, String city,
			String pincode, Date startDate, Date closeDate) {
		this.storeId = storeId;
		this.storeName = storeName;
		this.address = address;
		this.city = city;
		this.pincode = pincode;
		this.startDate = startDate;
		this.closeDate = closeDate;
	}

	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public String getEmpid() {
		return empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDate_1_1() {
		return date_1_1;
	}

	public void setDate_1_1(String date_1_1) {
		this.date_1_1 = date_1_1;
	}

	public String getDate_1_2() {
		return date_1_2;
	}

	public void setDate_1_2(String date_1_2) {
		this.date_1_2 = date_1_2;
	}

	public String getDate_1_3() {
		return date_1_3;
	}

	public void setDate_1_3(String date_1_3) {
		this.date_1_3 = date_1_3;
	}

	
	public void reset() {
		this.storeName = null;
		this.address = null;
		this.city = null;
		this.pincode = null;
		this.startDate = null;
		this.closeDate = null;
		this.date_1_1 = null;
		this.date_1_2 = null;
		this.date_1_3 = null;
	}
	
	@Override
	public String toString() {
		return "Store [storeId=" + storeId + ", storeName=" + storeName
				+ ", address1=" + address + ", city=" + city + ", state=" + state + ", country="
				+ country + ", pincode=" + pincode + ", startDate=" + startDate
				+ ", closeDate=" + closeDate + "]";
	}
}

src/pyramid/storehouse/pojo/Supplier.java
package pyramid.storehouse.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import pyramid.storehouse.vo.BaseForm;

public class Supplier extends BaseForm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2762709443758814799L;
	private int supplierId;
	private String supplierName;
	private String address;
	private String city;
	private String state;
	private String country;

	private String pincode;

	private String mobile;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date dateAdded;
	private Date dateModded;

	public Supplier() {
	}
	
	public Supplier(int supplierId, String supplierName, String address,
			String city, String state, String country, String pincode,
			Date startDate, Date closeDate, String mobile) {
		super();
		this.supplierId = supplierId;
		this.supplierName = supplierName;
		this.address = address;
		this.city = city;
		this.state = state;
		this.country = country;
		this.pincode = pincode;
		this.dateAdded = startDate;
		this.dateModded = closeDate;
		this.mobile = mobile;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public int getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPincode() {
		return pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public Date getDateAdded() {
		return dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Date getDateModded() {
		return dateModded;
	}

	public void setDateModded(Date dateModded) {
		this.dateModded = dateModded;
	}

	public void reset() {
		this.supplierName = null;
		this.address = null;
		this.city = null;
		this.pincode = null;
		this.dateAdded = null;
		this.dateModded = null;
		this.mobile = null;
	}
}

src/pyramid/storehouse/session/SessionBean.java
package pyramid.storehouse.session;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
 
public class SessionBean {
 
    public static HttpSession getSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }
 
    public static HttpServletRequest getRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance()
                .getExternalContext().getRequest();
    }
 
    public static String getUserName() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
        return session.getAttribute("username").toString();
    }
 
    public static String getUserId() {
        HttpSession session = getSession();
        if (session != null)
            return (String) session.getAttribute("userid");
        else
            return null;
    }
}

WebContent/jsf/disperse.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
	<script type="text/javascript" src="${request.contextPath}/javascript/utils.js"></script>
</h:head>
<h:body>

	<ui:composition template="/template/layout.xhtml">

		<ui:define name="header">
			<ui:include src="/jsf/menubar.xhtml" />
		</ui:define>

		<ui:define name="content">
			<h:form id="supplierForm">

				<h:panelGrid columns="2" >
					<p:panel header="#{stock.itemId!=null?'Edit Stock Disperse':'Stock disperse'}" style="width:850px;align:center;">
						<p:messages autoUpdate="true" />
						<h:panelGrid columns="3" id="supplierGrid" cellpadding="5"
							style="align:center">
							<p:outputLabel for="itemId" value="Item : " />
							<p:selectOneMenu id="itemId" value="#{stock.itemId}" requiredMessage="Item is mandatory "  required="true" style="width:205px" 
							 filter="true" filterMatchMode="startsWith">
								<p:ajax listener="#{stock.getStockUpdateFromDB()}" update=":supplierForm"  />
								<f:selectItem itemLabel="Select Item" itemValue="" noSelectionOption="true" />
                				<f:selectItems value="#{stock.items}" />
							</p:selectOneMenu>
							<p:outputLabel value="#{stock.stockUpdate}"  id="stockUpdate"/>

							<p:outputLabel for="quantity" value="Quantity : " />
							<p:inputText id="quantity" value="#{stock.quantity}" required="true" requiredMessage="Item quantity is mandatory " size="10">
								<f:validateLength minimum="1" maximum="5" />
								<f:validateLongRange minimum="1"/>
								<pe:keyFilter mask="num"/>  
							</p:inputText>
							<p:column />

							
							<p:outputLabel value="Volume" id="volLabel" for="volume" rendered="#{ stock.showVolume }"/>
							<p:inputText id="volume" value="#{stock.volume}" required="true" requiredMessage="Item volume is mandatory " size="10" rendered="#{ stock.showVolume }">
								<f:validateLength minimum="1" maximum="5" />
								<f:validateLongRange minimum="1"/>
								<pe:keyFilter mask="num"/>
							</p:inputText>
							<p:column rendered="#{ stock.showVolume }"/>
							
							<p:outputLabel for="remarks" value="Remarks : " />
							<p:inputText id="remarks" label="Remarks" value="#{stock.remarks}" >
							</p:inputText>
							<p:column />
						</h:panelGrid>
						
						<p:ajaxStatus onstart="PF('statusDialog').show()" oncomplete="PF('statusDialog').hide()" />

						<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
							closable="false" resizable="false" showHeader="false">
							<table>
								<tr>
									<td><h:outputText value="Please wait ..." /></td>
								</tr>
								<tr>
									<td><p:graphicImage name="/images/ajaxloadingbar.gif" />
									</td>
								</tr>
							</table>
						</p:dialog>

						<p:spacer width="10" />

						<br/>
						<p:spacer width="10" />
						<table width="95%">
							<tr>
								<td align="right">
									<p:commandButton icon="ui-icon-check"
										value="Save" ajax="true" validateClient="true"
										action="#{stock.disperse()}">
										<p:confirm header="Confirmation" message="Do you want to disperse ..?" icon="ui-icon-alert" />
									</p:commandButton>
								</td>
							</tr>
						</table>

					</p:panel>
				</h:panelGrid>
			</h:form>
		</ui:define>
	</ui:composition>

</h:body>

</html>

WebContent/jsf/emplist.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head>
	<script type="text/javascript" src="#{request.contextPath}/javascript/utils.js">
	</script>
</h:head>
<h:body>

	<ui:composition template="/template/layout.xhtml">

		<ui:define name="header">
			<ui:include src="/jsf/menubar.xhtml" />
		</ui:define>

		<ui:define name="content">

			<h:form id="empListForm">
				<input type="hidden" id="ck" name="ck" value="#{ck}" />

				<h:panelGrid columns="2">
					<p:panel header="Employee Search" style="width:850px;align:center;">
						<p:messages autoUpdate="true" />
						<h:panelGrid columns="4" id="matchGrid" cellpadding="5"
							style="align:center">
							<p:outputLabel for="colName" value="Select search field: " />
							<p:selectOneMenu id="colName" value="#{searchView.colName}" style="width:200px">
					            <f:selectItem itemLabel="Select One" itemValue="" />
					            <f:selectItem itemLabel="FIRST NAME" itemValue="fName" />
					            <f:selectItem itemLabel="LAST NAME" itemValue="lName" />
					            <f:selectItem itemLabel="EMAIL" itemValue="email" />
					            <f:selectItem itemLabel="MOBILE" itemValue="mobile" />
					        </p:selectOneMenu>
							<p:inputText id="searchCriteria" value="#{searchView.searchCriteria}"/>
							<p:commandButton icon="ui-icon-check" value="Search" ajax="true" update=":empListForm:empListGrid"
								validateClient="false" style="margin-right:10px"
								action="#{searchView.submitEmpSearch()}" />
						</h:panelGrid>
					</p:panel>
				</h:panelGrid>

				<h:panelGrid columns="2">
					<p:dataTable id="empListGrid" var="emp" value="#{searchView.emps}"
					widgetVar="myTable" rows="50" 
					 style="width:1600px;align:center;" scrollable="true" scrollHeight="400" resizableColumns="true" >
					<f:facet name="header">Employees</f:facet>

					<p:column headerText="ID" sortBy="#{emp.empId}" width="40">
						<h:outputText value="#{emp.empId}" />
					</p:column>
					<p:column headerText="First Name" filterBy="#{emp.firstName}">
						<h:outputText value="#{emp.firstName}" title="#{emp.firstName}" />
					</p:column>
					<p:column headerText="Last Name" width="90">
						<h:outputText value="#{emp.lastName}" />
					</p:column>
					<p:column headerText="Email" filterBy="#{emp.email}">
						<h:outputText value="#{emp.email}" title="#{emp.email}" />
					</p:column>
					<p:column headerText="Mobile" filterBy="#{emp.mobile}">
						<h:outputText value="#{emp.mobile}" title="#{emp.mobile}" />
					</p:column>
					<p:column headerText="Gender" rendered="false">
						<h:outputText value="#{emp.gender.equals('M')?'Male':'Female'}" /> 
					</p:column>
					<p:column headerText="Type" width="90" rendered="false">
						<h:outputText value="#{emp.type.equals('T')?'Temporary':'Permanent'}" />
					</p:column>
					<p:column headerText="Join Date" width="100">
						<h:outputText value="#{emp.joinDate}" />
					</p:column>
					<p:column headerText="Last Date" width="100" rendered="false">
						<h:outputText value="#{emp.lastDate}" />
					</p:column>
					<p:column headerText="Role">
						<h:outputText value="#{emp.roleName}" />
					</p:column>
					<p:column headerText="User Name" filterBy="#{emp.userName}">
						<h:outputText value="#{emp.userName}" />
					</p:column>
					<p:column headerText="Action" width="350">
						<p:commandButton action="#{employee.onEmployeeSelect}" value="EDIT" process="@this" immediate="true">
							<f:setPropertyActionListener target="#{employee.empId}" value="#{emp.empId}" />
						</p:commandButton>
						
						<p:commandButton action="#{employee.updateUserActiveStatus}" value="#{(emp.active == null || ('A').equals(emp.active))?'Deactivate':'Activate'}" process="@this" update=":empListForm:empListGrid">
							<f:setPropertyActionListener target="#{employee.empId}" value="#{emp.empId}" />
							<f:setPropertyActionListener target="#{employee.active}" value="#{emp.active}" />
						</p:commandButton>
						
						<p:commandButton action="#{UserView.showUserDialog()}" value="Create Login" process="@this" immediate="true" rendered="#{empty emp.userName}">
							<f:setPropertyActionListener target="#{UserView.empId}" value="#{emp.empId}" />
							<p:ajax event="dialogReturn" listener="#{searchView.submitEmpSearch()}" update=":empListForm:empListGrid"/>
						</p:commandButton>
						
						<p:commandButton action="#{UserView.showPasswordResetDialog()}" value="Change Password" process="@this" immediate="true" rendered="#{not empty emp.userName}">
							<f:setPropertyActionListener target="#{UserView.empId}" value="#{emp.empId}" />
						</p:commandButton>
					</p:column>
					<f:facet name="footer"> In total there are #{searchView.emps.size()} </f:facet> 
				</p:dataTable>
			</h:panelGrid>
		</h:form>
		</ui:define>
	</ui:composition>

</h:body>

</html>

WebContent/jsf/expired.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <title>Session expired</title>
        <meta http-equiv="refresh" content="0;url=#{request.contextPath}/jsf/login.xhtml" />
    </head>
    <body>
        <h1>Session expired</h1>
        <h3>You will be redirected to login page</h3>
        <p><a href="#{request.contextPath}/jsf/login.xhtml">Click here if redirect didn't work or when you're impatient</a>.</p>
    </body>
</html>

WebContent/jsf/grid.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
</h:head>
<h:body>

<h:form>
<p:dataTable var="car" value="#{dtBasicView.cars}" rows="2"
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15">
    <p:column headerText="Id" sortBy="#{car.id}">
        <h:outputText value="#{car.id}" />
    </p:column>
 
    <p:column headerText="Year" sortBy="#{car.year}">
        <h:outputText value="#{car.year}" />
    </p:column>
 
    <p:column headerText="Brand" sortBy="#{car.brand}">
        <h:outputText value="#{car.brand}" />
    </p:column>
 
    <p:column headerText="Color">
        <h:outputText value="#{car.color}" />
    </p:column>
</p:dataTable>
</h:form>
</h:body>
</html>